x<-1:10
y<-rnorm(10)
z<-exp(y)
ex.df<-data.frame(id=x,rn=y,exp.rn=z)
write.table(ex.df,file="C:/Classes/GeoStat/mydf.csv",sep=",")
ex2.df<-read.csv("C:/Classes/GeoStat/mydf.csv")

class(state.x77)
state77<-as.data.frame(state.x77)
colnames(state77)
hist(state77$Income, nclass=10, main="Income", col="light blue")
hist(state77$"HS Grad", main="High School", col="light blue")
boxplot(state77$Income)
plot(state77$'HS Grad', state77$Income, xlab="HS Grad", ylab="Income")
plot(state77[,c(2,3,5)])
qqnorm(state77$Income)
qqline(state77$Income)
state77.lm<-lm(state77$Income~state77$'HS Grad')
summary(state77.lm)
resids<-resid(state77.lm)
fits<-fitted(state77.lm)
par(mfrow=c(2,2))
plot(state77$'HS Grad', state77$Income, xlab="HS Grad", ylab="Income")
lines(state77$'HS Grad', fits)
plot(state77$"HS Grad", resids, ylab="Residuals")
abline(h=0)
hist(resids, xlab="Residuals")
qqnorm(resids, ylab="Residuals")
qqline(resids)
par(mfrow=c(1,1))

##assignment
crime<-read.csv("C:/Classes/GeoStat/crime.csv")
par(mfrow=c(1,2))
hist(crime$CRIME,breaks="Scott")
qqnorm(crime$CRIME)
qqline(crime$CRIME)

hist(crime$HOVAL,breaks="Scott")
hist(crime$INC,breaks="Scott")
